# vis.mac  –  interactive / visualisation macro

/vis/open OGL 600x600-0+0

/vis/drawVolume
/vis/viewer/set/viewpointThetaPhi 30 150

/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set mu- blue
/vis/modeling/trajectories/drawByParticleID-0/set mu+ cyan
/vis/modeling/trajectories/drawByParticleID-0/set e-  red
/vis/modeling/trajectories/drawByParticleID-0/set e+  green
/vis/modeling/trajectories/drawByParticleID-0/set gamma yellow

/vis/scene/endOfEventAction accumulate 20
/vis/viewer/set/autoRefresh true

/run/initialize
/run/beamOn 50
